waypoint_reconfigure_config:
  version: 1.0.0
  name: "description"
  default_local_inflation: 0.55 
  default_global_inflation: 0.55 
  default_trajectory_limit_vel: 1.0
  default_trajectory_limit_theta: 2.0 
  areas:
   - name: "2to6_saka"
     start_id: registed_0_1773749190996855168
     end_id: registed_0_1650549739750079712
     properties:
       - key: local_cost_cloud
         value: false
   - name: "hosoitoko1"
     start_id: registed_0_1650548559313191360
     end_id: registed_0_1773122637091871360
     properties:
       - key: trajectory_limit_vel
         value: 0.8
   - name: "hosoitoko2"
     start_id: registed_0_1773122674805135264
     end_id: registed_0_1773123030866639488
     properties:
        - key: trajectory_limit_vel
          value: 0.8
   - name: "pairon"
      start_id: registed_0_1773123030866639488
      end_id: registed_0_1650549932013220192
      properties:
        - key: trajectory_limit_vel
          value: 0.7
