waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1744525850871571040
      position:
        x: 11.35345
        y: 29.37979
        z: -3.000002
      euler_angles:
        x: -0
        y: 0
        z: 1.484477
    - id: 3
      position:
        x: -14.02234
        y: 6.811531
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: -0
      properties:
        - key: stop
          value: ""
      connections:
        - 1
    - id: 1
      position:
        x: 0.4895897
        y: 30.33562
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 0.0891088
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: true
      connections:
        - 2
    - id: registed_0_1650547097143051616
      position:
        x: -6.036432
        y: 1.723477
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_goal_4
      position:
        x: -27.66363
        y: -32.8257
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 3.079683
    - id: registed_0_1744525877836597312
      position:
        x: 3.205517
        y: 34.78989
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -3.0995
    - id: registed_0_1744525956331915328
      position:
        x: 0.6077309
        y: 30.50926
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: goal_radius
          value: 1.0
        - key: stop
          value: true
