waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_3_1650547538636924704
      position:
        x: 5.800507
        y: 5.587366
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 0.06863278
    - id: registed_2_1650547534526013024
      position:
        x: 2.943752
        y: 5.49438
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 0.02596672
    - id: registed_1_1650547524157884448
      position:
        x: -4.077238
        y: 5.551095
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -0.07195052
    - id: registed_goal_4
      position:
        x: -28.21153
        y: -30.58248
        z: -2.999998
      euler_angles:
        x: -0
        y: -0
        z: 3.079683
