waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: registed_0_1773122756710348576
      position:
        x: 110.8384
        y: 166.9075
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773119978920830944
      position:
        x: 52.53648
        y: 44.05009
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -0.3890997
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122687062915136
      position:
        x: 45.10703
        y: 175.3792
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123183352744096
      position:
        x: 138.0073
        y: 59.34322
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120322140390144
      position:
        x: 9.047535
        y: 71.34599
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -0.5106905
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120559935455584
      position:
        x: 122.6969
        y: 25.52654
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 1.20336
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122719016209824
      position:
        x: 64.88727
        y: 204.4
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123030866639488
      position:
        x: 108.1151
        y: 101.6383
        z: -2.999996
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123199769723200
      position:
        x: 83.4791
        y: -11.66827
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650547724366622816
      position:
        x: 32.29019
        y: 137.7545
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.959235
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773119812945760256
      position:
        x: -26.19128
        y: 31.83734
        z: -3.000003
      euler_angles:
        x: 0
        y: 0
        z: -0.5416917
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650545954256311520
      position:
        x: 98.13299
        y: 7.966728
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122648970325216
      position:
        x: 44.78183
        y: 141.683
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650545915335538528
      position:
        x: 122.2537
        y: 27.38538
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122728675583904
      position:
        x: 76.785
        y: 202.963
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650549739750079712
      position:
        x: 32.13746
        y: 12.96595
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 0.9285832
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525850871571040
      position:
        x: 72.80251
        y: -28.44892
        z: -2.999998
      euler_angles:
        x: -0
        y: 0
        z: 0.8401481
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123304441441248
      position:
        x: 13.61061
        y: -18.8553
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -2.038475
      properties:
        - key: stop
          value: true
    - id: registed_0_1773119866979233728
      position:
        x: 25.7274
        y: 2.241646
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: 0.8079934
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650549932013220192
      position:
        x: 112.6187
        y: 100.9262
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1773120604426749120
      position:
        x: 146.507
        y: 59.3372
        z: -2.999999
      euler_angles:
        x: -0
        y: 0
        z: 1.268106
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122674805135264
      position:
        x: 30.21053
        y: 157.2976
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122902191634496
      position:
        x: 83.79218
        y: 138.9128
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122853368447808
      position:
        x: 97.74866
        y: 147.2688
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123057924566048
      position:
        x: 130.3547
        y: 104.3196
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120925266394560
      position:
        x: 124.5555
        y: 147.189
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.876567
      properties:
        - key: stop
          value: ""
    - id: registed_0_1744525943053061792
      position:
        x: 133.0142
        y: 73.96796
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.545788
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650545973248391200
      position:
        x: 20.6151
        y: 4.845259
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -0.7363751
      properties:
        - key: stop
          value: true
    - id: registed_0_1773123072548282560
      position:
        x: 142.8838
        y: 101.7532
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650550277640111008
      position:
        x: 111.0481
        y: 101.0278
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122922615624256
      position:
        x: 72.20901
        y: 125.3824
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122666087789120
      position:
        x: 31.37453
        y: 153.9045
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120031909802656
      position:
        x: 67.85486
        y: 34.2887
        z: -3
      euler_angles:
        x: 9.154687e-08
        y: 1.860029e-07
        z: 0.7443982
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120069953213728
      position:
        x: 82.00796
        y: 46.34491
        z: -3
      euler_angles:
        x: 8.163988e-08
        y: 2.037697e-07
        z: 0.8497225
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122836914679968
      position:
        x: 102.4959
        y: 154.8143
        z: -3.000003
      euler_angles:
        x: 0
        y: 0
        z: -2.24183
      properties:
        - key: stop
          value: true
    - id: registed_0_1773123278376200960
      position:
        x: 23.65907
        y: -1.438614
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650548615439316160
      position:
        x: 122.5285
        y: 34.98399
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1773123239435192928
      position:
        x: 86.92557
        y: -23.88773
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123122068873664
      position:
        x: 41.27312
        y: 155.5851
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122708530134016
      position:
        x: 59.50905
        y: 193.7059
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122616921878656
      position:
        x: 83.15657
        y: 138.2657
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123080166791936
      position:
        x: 130.3964
        y: 92.89349
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122573132024512
      position:
        x: 101.389
        y: 152.3469
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120685200785536
      position:
        x: 145.8762
        y: 100.4945
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 1.654886
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650548007653825792
      position:
        x: 84.43338
        y: 116.7178
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1773122624900813120
      position:
        x: 72.18576
        y: 125.3227
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650550219941996320
      position:
        x: 99.88869
        y: 111.7048
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650548559313191360
      position:
        x: 134.9423
        y: 131.0225
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1773122678327395136
      position:
        x: 40.13753
        y: 174.1652
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120473710804768
      position:
        x: 85.99461
        y: 22.16426
        z: -3
      euler_angles:
        x: 7.451317e-08
        y: 2.09863e-07
        z: 0.939207
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120219362552064
      position:
        x: 67.99059
        y: 93.1953
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.705678
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122654980125728
      position:
        x: 35.81636
        y: 146.5275
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122826616437120
      position:
        x: 104.3393
        y: 161.8471
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123066323967072
      position:
        x: 135.1839
        y: 100.9093
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122637091871360
      position:
        x: 53.77839
        y: 136.1534
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120521476025472
      position:
        x: 91.48139
        y: 29.32154
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -0.3642699
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122696168458208
      position:
        x: 52.66203
        y: 189.7254
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120253246365152
      position:
        x: 34.1248
        y: 112.3372
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -2.431072
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123098740324480
      position:
        x: 30.35889
        y: 144.1056
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773749190996855168
      position:
        x: 28.99772
        y: 7.763334
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1773120396480327072
      position:
        x: 47.92386
        y: 47.67047
        z: -3.000002
      euler_angles:
        x: 0
        y: 0
        z: -0.6738706
      properties:
        - key: stop
          value: true
    - id: registed_0_1650547676243328160
      position:
        x: 22.53964
        y: -0.3934708
        z: -3.000005
      euler_angles:
        x: -0
        y: 0
        z: 0.8038393
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650550156334471072
      position:
        x: 62.05239
        y: 122.2413
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -3.084492
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773122589122318624
      position:
        x: 97.83367
        y: 147.0744
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773209660261353312
      position:
        x: 115.4291
        y: 89.77139
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650546275596860672
      position:
        x: 69.75143
        y: 33.27348
        z: -2.999999
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: registed_0_1773119930764950080
      position:
        x: 45.27608
        y: 32.10754
        z: -2.999999
      euler_angles:
        x: -0
        y: 0
        z: 0.8277927
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773121002950530624
      position:
        x: 113.439
        y: 144.0631
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650550119563377344
      position:
        x: 87.25153
        y: 106.7862
        z: -2.999998
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120126407938464
      position:
        x: 96.21849
        y: 75.21298
        z: -3
      euler_angles:
        x: 3.258412e-07
        y: 3.258414e-07
        z: 2.663315
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773119732612223424
      position:
        x: 15.39175
        y: 119.2468
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1650548610271488864
      position:
        x: 94.36674
        y: 185.2069
        z: -3.000001
      euler_angles:
        x: 0
        y: 0
        z: -1.57
    - id: 1
      position:
        x: 12.78197
        y: -16.23512
        z: -3.000004
      euler_angles:
        x: -0
        y: 0
        z: 0.0891088
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: true
      connections:
        - 2
    - id: registed_0_1650550198164430784
      position:
        x: 94.58163
        y: 127.5206
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120868399327104
      position:
        x: 146.8738
        y: 111.6429
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.135669
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773120968637913728
      position:
        x: 118.077
        y: 143.7315
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -3.055333
      properties:
        - key: stop
          value: ""
    - id: registed_0_1773123128749617664
      position:
        x: 139.7125
        y: 60.87767
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.57
      properties:
        - key: stop
          value: ""
